name             'codeigniter'
maintainer       'Thirdwave'
maintainer_email 'support@thirdwavellc.com'
license          'apachev2'
description      'Installs/Configures codeigniter'
long_description 'Installs/Configures codeigniter'
version          '0.1.0'

depends 'apt'
depends 'curl'
depends 'git'
depends 'php'
depends 'apache2'
depends 'mysql'
depends 'database'
